### ISSUE TITLE
Boost 1.57 support

### ISSUE THREAD

**Issue by klaufir** [vmilea/CppAwait#2]
The library in its current form doesn't compile with Boost 1.57 .

This is due the fact that Boost.Context have changed its API.

``` c++
typedef void* fcontext_t;
fcontext_t BOOST_CONTEXT_CALLDECL make_fcontext( void * sp, std::size_t size, void (* fn)( intptr_t) );
```

Previously `fcontext_t` was a struct - now it is simply a void\* . Also `minimum_stacksize()` and the likes have their own class now, namely `boost::coroutines::stack_traits`.

If you are not planning to upgrade to Boost 1.57, may ask some questions?
In Coro.cpp, what is the point of the line

``` c++
m->fc = new ctx::fcontext_t();
```

This only happens in the main coroutine. As far as I can tell, there is no default constructor for `fcontext_t`, so this does nothing except for allocating an area for the `fcontext_t` struct. This seems somewhat pointless because later on nothing uses this for the main coroutine. Even if I comment this line out, the examples still run fine.

Another thing, why did you not make `sCurrentCoro` thread_local ?

**Comment by vmilea** [comment]
Thanks, I've updated the library to use the current Boost.Context/Coroutine API.

`make_fcontext()` used to return a pointer to `fcontext_t`, so for consistency the main coroutine would allocate itself a dummy context on heap.

Regarding thread_local, there is not need. The library is single-threaded, like a GUI library. All async code runs on the main loop. To communicate with external threads you may use explicit synchronization or post messages to the scheduler.
